/**
 * Castle Layers behavior graph — deterministic config snapshot (code interpreter reads this).
 * Version bumps = evolution pipeline deploy unit (castle.layers.v1.x).
 * @see docs/RHIZOH_CASTLE_LAYERS_EVOLUTION_PIPELINE_V1.md
 */

export const CASTLE_LAYERS_BEHAVIOR_GRAPH_VERSION_V1 = "castle.layers.v1.1";

export const CASTLE_LAYER_STACK_ID_V1 = Object.freeze({
  L0_PERCEPTION: "L0_perception",
  L1_COGNITIVE: "L1_cognitive",
  L2_VOICE_DOMAIN: "L2_voice_domain",
  L3_SOCIAL_KERNEL: "L3_social_kernel",
  L4_EXECUTION: "L4_execution"
});

/** Voice log tag → stack layer (deterministic). */
export const CASTLE_VOICE_EVENT_LAYER_MAP_V1 = Object.freeze({
  STT_SESSION_BEGIN: CASTLE_LAYER_STACK_ID_V1.L0_PERCEPTION,
  STT_RESULT: CASTLE_LAYER_STACK_ID_V1.L0_PERCEPTION,
  STT_FINAL: CASTLE_LAYER_STACK_ID_V1.L0_PERCEPTION,
  STT_INTERIM: CASTLE_LAYER_STACK_ID_V1.L0_PERCEPTION,
  STT_TEMPORAL: CASTLE_LAYER_STACK_ID_V1.L0_PERCEPTION,
  STT_DISPATCH_REJECT: CASTLE_LAYER_STACK_ID_V1.L1_COGNITIVE,
  STT_DISPATCH_BLOCKED: CASTLE_LAYER_STACK_ID_V1.L1_COGNITIVE,
  GATE_CONFIDENCE_ROUTER: CASTLE_LAYER_STACK_ID_V1.L1_COGNITIVE,
  GATE_ROUTER_SANITY_REJECT: CASTLE_LAYER_STACK_ID_V1.L1_COGNITIVE,
  GATE_ROUTER_REJECT: CASTLE_LAYER_STACK_ID_V1.L1_COGNITIVE,
  GATE_TURN: CASTLE_LAYER_STACK_ID_V1.L1_COGNITIVE,
  WITNESS: CASTLE_LAYER_STACK_ID_V1.L2_VOICE_DOMAIN,
  DIRECTED_SPEECH_CLASSIFIER: CASTLE_LAYER_STACK_ID_V1.L2_VOICE_DOMAIN,
  ATTENTION_CONTEXT: CASTLE_LAYER_STACK_ID_V1.L2_VOICE_DOMAIN,
  RELATIONSHIP_KERNEL: CASTLE_LAYER_STACK_ID_V1.L3_SOCIAL_KERNEL,
  MUTUAL_FAMILIARITY: CASTLE_LAYER_STACK_ID_V1.L3_SOCIAL_KERNEL,
  BEHAVIOR_COMMITMENT: CASTLE_LAYER_STACK_ID_V1.L3_SOCIAL_KERNEL,
  STT_DISPATCH: CASTLE_LAYER_STACK_ID_V1.L4_EXECUTION,
  STT_DISPATCH_SCOPE_REJECT: CASTLE_LAYER_STACK_ID_V1.L2_VOICE_DOMAIN,
  STT_DISPATCH_LAYER_REJECT: CASTLE_LAYER_STACK_ID_V1.L4_EXECUTION,
  VOICE_V3_SESSION_BEGIN: CASTLE_LAYER_STACK_ID_V1.L0_PERCEPTION,
  VOICE_V3_LAYER_STREAM_DENIED: CASTLE_LAYER_STACK_ID_V1.L2_VOICE_DOMAIN,
  VOICE_LLM_DISPATCH: CASTLE_LAYER_STACK_ID_V1.L4_EXECUTION,
  VOICE_LLM_DISPATCH_FAIL: CASTLE_LAYER_STACK_ID_V1.L4_EXECUTION
});

/** Unknown scope → shadow-only (no UI execution). */
export const CASTLE_LAYER_SCOPE_UNKNOWN_POLICY_V1 = "shadow_only";

/**
 * @param {string} eventTag
 * @returns {string}
 */
export function mapCastleVoiceEventTagToLayerV1(eventTag) {
  const key = String(eventTag || "")
    .trim()
    .replace(/^VOICE_/, "")
    .toUpperCase();
  return CASTLE_VOICE_EVENT_LAYER_MAP_V1[key] || CASTLE_LAYER_STACK_ID_V1.L2_VOICE_DOMAIN;
}
