param(
  [string]$ArchiveRoot = "C:\Users\LENOVO\Desktop\castle\docs\archive\llm-chats",
  [string]$BatchId,
  [string[]]$InboxFiles,
  [switch]$RescanInbox
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "lib\llm-chat-layer-scan.ps1")

function Load-Policy {
  param([string]$Path)
  if (-not (Test-Path -LiteralPath $Path)) {
    throw "Policy file not found: $Path"
  }
  return (Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json)
}

function Get-AllowedWriteActions {
  param($Policy, [string]$LayerId)
  $layer = $Policy.layers.$LayerId
  if (-not $layer) { return @() }
  $allowed = @()
  if ($layer.scan) { $allowed += 'scan' }
  if ($layer.annotate) { $allowed += 'annotate' }
  if ($layer.staging_write) { $allowed += 'staging_write' }
  if ($layer.canonical_write) { $allowed += 'canonical_write' }
  if ($layer.execution_write) { $allowed += 'execution_write' }
  return $allowed
}

function Update-FileFrontmatter {
  param(
    [string]$Path,
    [object]$LayerScan,
    [string]$AllowedWrites
  )
  $raw = Get-Content -LiteralPath $Path -Raw
  if ($raw -notmatch '(?s)^---\r?\n(.*?)\r?\n---\r?\n(.*)$') {
    return
  }

  $body = $Matches[2]
  $hitsYaml = Format-LayerHitsYaml -Hits $LayerScan.layer_hits
  $keep = @(
    $Matches[1] -split "`n" |
      Where-Object {
        $_ -notmatch '^(layer_primary|layer_hits|layer_hit_total|tonom_allowed_writes):'
      }
  )
  $keep += @(
    "layer_primary: $($LayerScan.layer_primary)",
    "layer_hits: $hitsYaml",
    "layer_hit_total: $($LayerScan.layer_hit_total)",
    "tonom_allowed_writes: $AllowedWrites"
  )
  $newFm = ($keep -join "`n").Trim()
  Set-Content -LiteralPath $Path -Value ("---`n$newFm`n---`n$body") -Encoding UTF8
}

function Write-StagingNote {
  param(
    [string]$StagingDir,
    [string]$FileName,
    [object]$LayerScan,
    [string[]]$AllowedStagingLayers
  )
  if ($AllowedStagingLayers.Count -eq 0) { return $null }
  $notePath = Join-Path $StagingDir (($FileName -replace '\.md$','') + '_staging.md')
  $content = @(
    '# Staging note (auto)'
    ''
    "source_file: $FileName"
    "primary_layers: $($LayerScan.layer_primary)"
    "allowed_staging_layers: $($AllowedStagingLayers -join ', ')"
    ''
    '## Layer hits'
    ''
  )
  foreach ($k in $LayerScan.layer_hits.Keys | Sort-Object) {
    $content += ('- {0}: {1}' -f $k, $LayerScan.layer_hits[$k])
  }
  $content += ''
  $content += '_Non-authoritative. Human gate required for canonical promotion._'
  Set-Content -LiteralPath $notePath -Value ($content -join [Environment]::NewLine) -Encoding UTF8
  return $notePath
}

function Update-LayerIndex {
  param([string]$ArchiveRoot)
  $inbox = Join-Path $ArchiveRoot 'inbox'
  $all = Get-ChildItem -LiteralPath $inbox -File -Filter '*.md' -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending

  $indexPath = Join-Path $ArchiveRoot 'LLM_CHAT_ARCHIVE_INDEX_V0.md'
  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add('# LLM Chat Archive Index (V0)') | Out-Null
  $lines.Add('') | Out-Null
  $lines.Add('_Auto-generated by scripts/apply-llm-chat-tonom-write.ps1_') | Out-Null
  $lines.Add('') | Out-Null
  $lines.Add("Updated: $((Get-Date).ToString('yyyy-MM-dd HH:mm:ss'))") | Out-Null
  $lines.Add("Total files: $($all.Count)") | Out-Null
  $lines.Add('') | Out-Null
  $lines.Add('| File | Source | Quality | Primary layers | Layer hits | Tonom writes |') | Out-Null
  $lines.Add('|---|---|---|---|---|---|') | Out-Null

  foreach ($f in $all) {
    $raw = Get-Content -LiteralPath $f.FullName -Raw
    $src = 'unknown'
    $quality = 'substantial'
    $primary = ''
    $hits = ''
    $writes = ''
    if ($raw -match 'source_hint:\s*(\S+)') { $src = $Matches[1] }
    if ($raw -match 'quality:\s*(\S+)') { $quality = $Matches[1] }
    if ($raw -match 'layer_primary:\s*(.*)') { $primary = $Matches[1].Trim() }
    if ($raw -match 'layer_hits:\s*(.*)') { $hits = $Matches[1].Trim() }
    if ($raw -match 'tonom_allowed_writes:\s*(.*)') { $writes = $Matches[1].Trim() }
    $lines.Add("| ``$($f.Name)`` | $src | $quality | $primary | $hits | $writes |") | Out-Null
  }

  $lines.Add('') | Out-Null
  $lines.Add('## Policy') | Out-Null
  $lines.Add('') | Out-Null
  $lines.Add('- `docs/archive/llm-chats/tonom-write-policy.v0.json`') | Out-Null
  $lines.Add('- `docs/LLM_CHAT_LAYER_TONOM_WRITE_POLICY_V0.md`') | Out-Null

  Set-Content -LiteralPath $indexPath -Value ($lines -join [Environment]::NewLine) -Encoding UTF8
  return $indexPath
}

$policyPath = Join-Path $ArchiveRoot 'tonom-write-policy.v0.json'
$stagingDir = Join-Path $ArchiveRoot 'staging'
$inboxDir = Join-Path $ArchiveRoot 'inbox'
if (-not (Test-Path -LiteralPath $stagingDir)) {
  New-Item -ItemType Directory -Path $stagingDir | Out-Null
}

$policy = Load-Policy -Path $policyPath
$targets = @()

if ($RescanInbox) {
  $targets = Get-ChildItem -LiteralPath $inboxDir -File -Filter '*.md' -ErrorAction SilentlyContinue
} elseif ($InboxFiles -and $InboxFiles.Count -gt 0) {
  $targets = $InboxFiles | ForEach-Object { Get-Item -LiteralPath $_ }
} elseif ($BatchId) {
  $targets = Get-ChildItem -LiteralPath $inboxDir -File -Filter '*.md' |
    Where-Object { (Get-Content -LiteralPath $_.FullName -Raw) -match "batch_id:\s*$BatchId" }
} else {
  throw 'Provide -BatchId, -InboxFiles, or -RescanInbox.'
}

$batchLayerTotals = @{}
$processed = 0

foreach ($f in $targets) {
  $text = Get-Content -LiteralPath $f.FullName -Raw
  $scan = Scan-ChatLayers -Text $text

  $allowedAll = New-Object System.Collections.Generic.List[string]
  $stagingLayers = New-Object System.Collections.Generic.List[string]

  foreach ($layerId in $scan.layer_hits.Keys) {
    $hit = $scan.layer_hits[$layerId]
    if ($hit -gt 0) {
      if (-not $batchLayerTotals.ContainsKey($layerId)) { $batchLayerTotals[$layerId] = 0 }
      $batchLayerTotals[$layerId] += $hit

      $allowed = Get-AllowedWriteActions -Policy $policy -LayerId $layerId
      foreach ($a in $allowed) {
        if ($allowedAll -notcontains $a) { $allowedAll.Add($a) | Out-Null }
      }
      if ($policy.layers.$layerId.staging_write) {
        $stagingLayers.Add($layerId) | Out-Null
      }
    }
  }

  $allowedStr = ($allowedAll | Sort-Object) -join ','
  Update-FileFrontmatter -Path $f.FullName -LayerScan $scan -AllowedWrites $allowedStr
  Write-StagingNote -StagingDir $stagingDir -FileName $f.Name -LayerScan $scan -AllowedStagingLayers @($stagingLayers)
  $processed++
}

$policy.state.last_batch_id = if ($BatchId) { $BatchId } else { $policy.state.last_batch_id }
$policy.state.last_updated_utc = (Get-Date).ToUniversalTime().ToString('o')
$policy.state.total_ingested = [int]$policy.state.total_ingested + $processed

$layerHits = @{}
if ($policy.state.layer_hits) {
  $policy.state.layer_hits.PSObject.Properties | ForEach-Object {
    $layerHits[$_.Name] = [int]$_.Value
  }
}
foreach ($k in $batchLayerTotals.Keys) {
  if (-not $layerHits.ContainsKey($k)) { $layerHits[$k] = 0 }
  $layerHits[$k] = $layerHits[$k] + [int]$batchLayerTotals[$k]
}
$policy.state.layer_hits = $layerHits

$policy | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $policyPath -Encoding UTF8
$indexPath = Update-LayerIndex -ArchiveRoot $ArchiveRoot

$analyticsDir = Join-Path (Split-Path -Path $ArchiveRoot -Parent) "spiralmmo-intelligence"
if (-not (Test-Path -LiteralPath $analyticsDir)) {
  New-Item -ItemType Directory -Path $analyticsDir | Out-Null
}
$snapshotPath = Join-Path $analyticsDir "temporal-snapshots.jsonl"
foreach ($f in $targets) {
  $raw = Get-Content -LiteralPath $f.FullName -Raw
  $utc = (Get-Date).ToUniversalTime().ToString("o")
  if ($raw -match 'archived_at_utc:\s*(\S+)') { $utc = $Matches[1] }
  $hits = ""
  if ($raw -match 'layer_hits:\s*(.*)') { $hits = $Matches[1].Trim() }
  $line = (@{ timestamp_utc = $utc; file = $f.Name; layer_hits = $hits } | ConvertTo-Json -Compress)
  Add-Content -LiteralPath $snapshotPath -Value $line -Encoding UTF8
}

Write-Output "TONOM_APPLIED=true"
Write-Output "PROCESSED=$processed"
Write-Output "POLICY=$policyPath"
Write-Output "INDEX=$indexPath"
