# T0 full interface dev — cloud gateway, research overlays OFF by default.
# Usage: powershell -File scripts/setup-rhizoh-t0-dev.ps1
# Local gateway: -Local

param(
  [switch]$Local,
  [string]$RepoRoot = "",
  [string]$GatewayHost = "https://castle-genesis-rhizoh-habitatos.onrender.com",
  [string]$GatewayToken = "castle_dev_token_2026",
  [string]$CesiumIonToken = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ($Local) {
  $GatewayHost = "http://localhost:8090"
}

$root = if ($RepoRoot.Trim()) { $RepoRoot.Trim() } else { Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path) }
$envLocal = Join-Path $root "apps\client\.env.local"

$ws = $GatewayHost -replace '^https:', 'wss:' -replace '^http:', 'ws:'
$llm = "$($GatewayHost.TrimEnd('/'))/rhizoh/llm"

$lines = @(
  "# Auto-generated by scripts/setup-rhizoh-t0-dev.ps1 (T0 lock)",
  "VITE_RHIZOH_LEGAL_PREAMBLE=0",
  "",
  "# T0 monolith - world stack always on; no genesis text-only shell",
  "VITE_WORLD_LAYER=1",
  "VITE_WORLD_EXECUTION_MODE=active",
  "",
  "# Product shell: debug umbrella OFF; research nodes need explicit granular flags",
  "VITE_DEBUG=0",
  "VITE_SATELLITE_NODE_REGISTRY_V0=0",
  "VITE_SOVEREIGN_NODE_ONBOARDING=0",
  "VITE_EPISTEMIC_GRAPH_VIZ_V0=0",
  "VITE_EPISTEMIC_SIM_RESEARCH=0",
  "",
  "VITE_GATEWAY_HTTP=$llm",
  "VITE_RHIZOH_LLM_HTTP=$llm",
  "VITE_GATEWAY_WS=$ws",
  "VITE_LIVE_GATEWAY_BASE=$($GatewayHost.TrimEnd('/'))",
  "VITE_GATEWAY_TOKEN=$GatewayToken",
  "VITE_PREFER_LOCAL_GATEWAY=$([int][bool]$Local)",
  "VITE_CASTLE_APP_ID=castle-vnext-core"
)

if ($CesiumIonToken.Trim()) {
  $lines += "VITE_CESIUM_ION_TOKEN=$($CesiumIonToken.Trim())"
} else {
  $lines += "# VITE_CESIUM_ION_TOKEN=  # optional; OSM works without Ion"
}

Set-Content -Path $envLocal -Value ($lines -join "`n") -Encoding UTF8

Write-Host "OK T0 dev env: $envLocal" -ForegroundColor Green
Write-Host "Gateway: $GatewayHost"
Write-Host ""
Write-Host "Run:"
Write-Host "  npm run dev -w apps/client"
Write-Host ""
if ($Local) {
  Write-Host "Local mode: also run gateway in another terminal." -ForegroundColor Yellow
}
