# T0 staging preview — full interface + observability, no legal/cohort gate.
# Usage: powershell -File scripts/setup-rhizoh-t0-staging.ps1
#        powershell -File scripts/setup-rhizoh-t0-staging.ps1 -FromMainLocal

param(
  [string]$RepoRoot = "",
  [string]$GatewayHost = "https://castle-genesis-rhizoh-habitatos.onrender.com",
  [string]$GatewayToken = "castle_dev_token_2026",
  [switch]$FromMainLocal
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$castleMain = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$root = if ($RepoRoot.Trim()) { $RepoRoot.Trim() } else { $castleMain }

$localExtras = @{}
if ($FromMainLocal) {
  $localEnv = Join-Path $castleMain "apps\client\.env.local"
  if (-not (Test-Path $localEnv)) {
    $localBak = Join-Path $castleMain "apps\client\.env.local.build-bak"
    if (Test-Path $localBak) { $localEnv = $localBak }
  }
  if (Test-Path $localEnv) {
    foreach ($line in Get-Content $localEnv) {
      if ($line -match '^\s*VITE_GATEWAY_TOKEN=(.+)$') { $GatewayToken = $matches[1].Trim() }
      if ($line -match '^\s*VITE_LIVE_GATEWAY_BASE=(.+)$') { $GatewayHost = $matches[1].Trim() }
      if ($line -match '^\s*(VITE_\w+)=(.+)$') {
        $localExtras[$matches[1]] = $matches[2].Trim()
      }
    }
  }
}

$ws = $GatewayHost -replace '^https:', 'wss:' -replace '^http:', 'ws:'
$llm = "$($GatewayHost.TrimEnd('/'))/rhizoh/llm"
$envProd = Join-Path $root "apps\client\.env.production"

$lines = @(
  "# Auto-generated by scripts/setup-rhizoh-t0-staging.ps1",
  "# Staging preview: T0 + companion observability, gates OFF.",
  "",
  "VITE_WORLD_LAYER=1",
  "VITE_WORLD_EXECUTION_MODE=active",
  "VITE_RHIZOH_SPATIAL_SHELL=0",
  "",
  "VITE_GATEWAY_HTTP=$llm",
  "VITE_RHIZOH_LLM_HTTP=$llm",
  "VITE_GATEWAY_WS=$ws",
  "VITE_LIVE_GATEWAY_BASE=$($GatewayHost.TrimEnd('/'))",
  "VITE_GATEWAY_TOKEN=$GatewayToken",
  "VITE_PREFER_LOCAL_GATEWAY=0",
  "VITE_CASTLE_APP_ID=castle-vnext-core",
  "",
  "VITE_DEBUG=1",
  "VITE_RHIZOH_T0_FIRST_MATCH=1",
  "VITE_CASTLE_LAYERS_DEBUG=1",
  "VITE_PRESENCE_MESH=0",
  "VITE_SATELLITE_NODE_REGISTRY_V0=0",
  "VITE_SOVEREIGN_NODE_ONBOARDING=0",
  "",
  "VITE_RHIZOH_FAST_SPEECH_MODE=1",
  "# Companion anchor fox_v1 - matches production setup-rhizoh-t0-production.ps1",
  "VITE_RHIZOH_CONVERSATION_ANCHOR_SPECIES=fox_v1",
  "VITE_RHIZOH_VOICE_ENGINE_V3=1",
  "VITE_RHIZOH_VOICE_WITNESS_SHADOW=1",
  "VITE_RHIZOH_VOICE_ENV_PROFILE=1",
  "",
  "# Staging: skip legal/cohort ingress",
  "VITE_RHIZOH_LEGAL_PREAMBLE=0",
  "VITE_RHIZOH_CLOSED_ADMISSION=0",
  "VITE_RHIZOH_INVITE_ONLY_GOOGLE=0",
  "VITE_ONTOLOGICAL_BOOT_GATE=0",
  "VITE_RHIZOH_COHORT_SERVER_GATE=0",
  "",
  "VITE_RHIZOH_DEFAULT_LOCALE=en",
  "VITE_RHIZOH_OUTPUT_LANGUAGE_POLICY=ui_locked_output",
  "VITE_RHIZOH_REQUIRE_LANGUAGE_PICKER=0",
  "",
  "VITE_RHIZOH_SURFACE_CREATIVE=1",
  "VITE_RHIZOH_ENTITY_PROJECTION_MAP=1",
  "VITE_CESIUM_WORLD_PROJECTION_BIND=1",
  "VITE_CESIUM_OSM_BUILDINGS=1",
  "VITE_CESIUM_WORLD_TERRAIN=1",
  "VITE_CESIUM_BOOT_DIAG=1",
  "",
  "VITE_CASTLE_AUTHORITY_PROFILE=staging"
)

function Add-FirebaseSdkLinesFromJson {
  param([string]$JsonText)
  try {
    $fb = $JsonText | ConvertFrom-Json
    if (-not $fb.apiKey) { return }
    $cfg = @{
      apiKey = $fb.apiKey
      authDomain = $fb.authDomain
      projectId = $fb.projectId
      storageBucket = $fb.storageBucket
      messagingSenderId = $fb.messagingSenderId
      appId = $fb.appId
    }
    if ($fb.measurementId) { $cfg.measurementId = $fb.measurementId }
    if ($fb.databaseURL) { $cfg.databaseURL = $fb.databaseURL }
    $oneLine = ($cfg | ConvertTo-Json -Compress)
    $script:lines += "VITE_FIREBASE_CONFIG=$oneLine"
    $script:lines += "VITE_FIREBASE_API_KEY=$($fb.apiKey)"
    $script:lines += "VITE_FIREBASE_AUTH_DOMAIN=$($fb.authDomain)"
    $script:lines += "VITE_FIREBASE_PROJECT_ID=$($fb.projectId)"
    $script:lines += "VITE_FIREBASE_STORAGE_BUCKET=$($fb.storageBucket)"
    $script:lines += "VITE_FIREBASE_MESSAGING_SENDER_ID=$($fb.messagingSenderId)"
    $script:lines += "VITE_FIREBASE_APP_ID=$($fb.appId)"
    if ($fb.measurementId) { $script:lines += "VITE_FIREBASE_MEASUREMENT_ID=$($fb.measurementId)" }
    if ($fb.databaseURL) { $script:lines += "VITE_FIREBASE_DATABASE_URL=$($fb.databaseURL)" }
  } catch {
    Write-Warning "Firebase SDK JSON parse failed: $_"
  }
}

$firebaseMerged = $false
if ($FromMainLocal -and $localExtras) {
  foreach ($key in @(
    'VITE_CESIUM_ION_TOKEN',
    'VITE_OPENWEATHER_API_KEY',
    'VITE_OPENWEATHER_LAT',
    'VITE_OPENWEATHER_LON',
    'VITE_TOMTOM_API_KEY',
    'VITE_REAL_LAYER_WEATHER_INGRESS',
    'VITE_REAL_LAYER_TRAFFIC_INGRESS',
    'VITE_FIREBASE_CONFIG',
    'VITE_FIREBASE_API_KEY',
    'VITE_FIREBASE_APP_ID',
    'VITE_FIREBASE_MESSAGING_SENDER_ID'
  )) {
    if ($localExtras.ContainsKey($key) -and $localExtras[$key]) {
      $lines += "$key=$($localExtras[$key])"
      if ($key -match '^VITE_FIREBASE') { $firebaseMerged = $true }
    }
  }
}

if (-not $firebaseMerged) {
  $prevProd = Join-Path $castleMain "apps\client\.env.production"
  if (Test-Path $prevProd) {
    foreach ($line in Get-Content $prevProd) {
      if ($line -match '^\s*VITE_FIREBASE_CONFIG=(.+)$') {
        Add-FirebaseSdkLinesFromJson -JsonText $matches[1].Trim()
        $firebaseMerged = $true
        break
      }
    }
  }
}

Set-Content -Path $envProd -Value ($lines -join "`n") -Encoding UTF8
Write-Host "OK staging env: $envProd" -ForegroundColor Green
Write-Host "Build: npm run build -w apps/client"
