# T0 rhizoh.com production build env — gateway + legal/cohort (NOT .env.local dev shortcuts).
# Usage: powershell -File scripts/setup-rhizoh-t0-production.ps1
#        powershell -File scripts/setup-rhizoh-t0-production.ps1 -RepoRoot ..\castle-t0-interface

param(
  [string]$RepoRoot = "",
  [string]$GatewayHost = "https://castle-genesis-rhizoh-habitatos.onrender.com",
  [string]$GatewayToken = "castle_dev_token_2026",
  [string]$CohortAllowlist = "",
  [switch]$FromMainLocal
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$castleMain = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$root = if ($RepoRoot.Trim()) { $RepoRoot.Trim() } else { $castleMain }

if ($FromMainLocal) {
  $localEnv = Join-Path $castleMain "apps\client\.env.local"
  if (Test-Path $localEnv) {
    foreach ($line in Get-Content $localEnv) {
      if ($line -match '^\s*VITE_GATEWAY_TOKEN=(.+)$') { $GatewayToken = $matches[1].Trim() }
      if ($line -match '^\s*VITE_LIVE_GATEWAY_BASE=(.+)$') { $GatewayHost = $matches[1].Trim() }
    }
  }
}

$ws = $GatewayHost -replace '^https:', 'wss:' -replace '^http:', 'ws:'
$llm = "$($GatewayHost.TrimEnd('/'))/rhizoh/llm"
$envProd = Join-Path $root "apps\client\.env.production"

$lines = @(
  "# Auto-generated by scripts/setup-rhizoh-t0-production.ps1",
  "# DO NOT set VITE_RHIZOH_LEGAL_PREAMBLE=0 (rhizoh.com requires legal preamble in prod builds).",
  "",
  "VITE_WORLD_LAYER=1",
  "VITE_WORLD_EXECUTION_MODE=active",
  "",
  "VITE_GATEWAY_HTTP=$llm",
  "VITE_RHIZOH_LLM_HTTP=$llm",
  "VITE_GATEWAY_WS=$ws",
  "VITE_LIVE_GATEWAY_BASE=$($GatewayHost.TrimEnd('/'))",
  "VITE_GATEWAY_TOKEN=$GatewayToken",
  "VITE_PREFER_LOCAL_GATEWAY=0",
  "VITE_CASTLE_APP_ID=castle-vnext-core",
  "",
  "VITE_DEBUG=0",
  "VITE_SATELLITE_NODE_REGISTRY_V0=0",
  "VITE_SOVEREIGN_NODE_ONBOARDING=0",
  "",
  "# Voice Engine v3 - MediaRecorder + gateway Whisper/Google STT",
  "VITE_RHIZOH_VOICE_ENGINE_V3=1",
  "VITE_RHIZOH_VOICE_WITNESS_SHADOW=1",
  "VITE_RHIZOH_VOICE_ATTENTION_MODE=moving_context",
  "VITE_RHIZOH_SHARED_ATTENTION_TYPE=co_presence",
  "",
  "# Ingress: legal auto-on for rhizoh.com PROD; cohort step when closed admission enabled",
  "VITE_RHIZOH_CLOSED_ADMISSION=1",
  "VITE_RHIZOH_INVITE_ONLY_GOOGLE=1",
  "VITE_ONTOLOGICAL_BOOT_GATE=0"
)

if ($CohortAllowlist.Trim()) {
  $lines += "VITE_RHIZOH_COHORT_EMAIL_ALLOWLIST=$($CohortAllowlist.Trim())"
} else {
  $lines += "# VITE_RHIZOH_COHORT_EMAIL_ALLOWLIST=you@example.com"
}

$lines += @(
  "",
  "# Firebase: copy VITE_FIREBASE_CONFIG from main apps/client/.env.production if needed"
)

if ($FromMainLocal) {
  $mainProd = Join-Path $castleMain "apps\client\.env.production"
  if (Test-Path $mainProd) {
    foreach ($line in Get-Content $mainProd) {
      if ($line -match '^\s*VITE_FIREBASE_CONFIG=(.+)$') {
        $lines += "VITE_FIREBASE_CONFIG=$($matches[1].Trim())"
      }
      if ($line -match '^\s*VITE_CESIUM_ION_TOKEN=(.+)$') {
        $lines += "VITE_CESIUM_ION_TOKEN=$($matches[1].Trim())"
      }
    }
  }
}

Set-Content -Path $envProd -Value ($lines -join "`n") -Encoding UTF8
Write-Host "OK $envProd" -ForegroundColor Green
Write-Host "Fill VITE_FIREBASE_CONFIG if Google/cohort auth needed."
Write-Host "Build: npm run build -w apps/client"
