# Rhizoh spatial dev — cloud gateway by default (single command: npm run dev:spatial)
# Local gateway: powershell -File scripts/setup-rhizoh-spatial-dev.ps1 -Local

param(
  [switch]$Local,
  [string]$GatewayHost = "https://castle-genesis-rhizoh-habitatos.onrender.com",
  [string]$GatewayToken = "castle_dev_token_2026",
  [string]$CesiumIonToken = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ($Local) {
  $GatewayHost = "http://localhost:8090"
}

$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$envLocal = Join-Path $root "apps\client\.env.local"

$ws = $GatewayHost -replace '^https:', 'wss:' -replace '^http:', 'ws:'
$llm = "$($GatewayHost.TrimEnd('/'))/rhizoh/llm"

$lines = @(
  "# Auto-generated by scripts/setup-rhizoh-spatial-dev.ps1",
  "VITE_RHIZOH_LEGAL_PREAMBLE=0",
  "VITE_WORLD_LAYER=1",
  "VITE_WORLD_EXECUTION_MODE=active",
  "",
  "# VITE_DEBUG=1 unlocks research overlays (Kadikoy/Barcelona graph) in dev — keep off for product shell",
  "VITE_DEBUG=0",
  "VITE_SATELLITE_NODE_REGISTRY_V0=0",
  "VITE_SOVEREIGN_NODE_ONBOARDING=0",
  "VITE_EPISTEMIC_GRAPH_VIZ_V0=0",
  "",
  "VITE_GATEWAY_HTTP=$llm",
  "VITE_RHIZOH_LLM_HTTP=$llm",
  "VITE_GATEWAY_WS=$ws",
  "VITE_LIVE_GATEWAY_BASE=$($GatewayHost.TrimEnd('/'))",
  "VITE_GATEWAY_TOKEN=$GatewayToken",
  "VITE_PREFER_LOCAL_GATEWAY=$([int][bool]$Local)"
)

if ($CesiumIonToken.Trim()) {
  $lines += "VITE_CESIUM_ION_TOKEN=$($CesiumIonToken.Trim())"
} else {
  $lines += "# VITE_CESIUM_ION_TOKEN=  # optional; OSM imagery works without it"
}

Set-Content -Path $envLocal -Value ($lines -join "`n") -Encoding UTF8

Write-Host "OK wrote $envLocal" -ForegroundColor Green
Write-Host "Gateway: $GatewayHost"
Write-Host ""
Write-Host "Run (client only — cloud gateway, no second terminal):"
Write-Host "  npm run dev:spatial"
Write-Host ""
if ($Local) {
  Write-Host "Local mode: also run npm run dev:gateway in another terminal." -ForegroundColor Yellow
}
