/**
 * Regenerate scripts/runtimeSnapshotV1.topLevelKeys.lock.json from source.
 * Run after intentionally changing top-level keys in buildRuntimeSnapshotV1().
 *
 *   node scripts/syncRuntimeSnapshotV1TopLevelLock.mjs
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { extractTopLevelSnapKeysFromSource } from "./runtimeSnapshotV1SnapBlockParse.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const snapPath = path.join(repoRoot, "apps", "client", "src", "rhizoh", "runtime", "runtimeSnapshotV1.js");
const lockPath = path.join(repoRoot, "scripts", "runtimeSnapshotV1.topLevelKeys.lock.json");

const src = fs.readFileSync(snapPath, "utf8");
const { ok, keys, error } = extractTopLevelSnapKeysFromSource(src);
if (!ok) {
  console.error(`[SNAPSHOT_LOCK_SYNC] failed: ${error}`);
  process.exit(1);
}

const payload = {
  _comment:
    "Top-level keys of buildRuntimeSnapshotV1() snap object — regenerated by: node scripts/syncRuntimeSnapshotV1TopLevelLock.mjs",
  topLevelKeys: keys
};

fs.writeFileSync(lockPath, `${JSON.stringify(payload, null, 2)}\n`, "utf8");
console.log(`[SNAPSHOT_LOCK_SYNC] wrote ${keys.length} keys → ${path.relative(repoRoot, lockPath)}`);
